package spanish.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public class graDinamicaSolicitudDato extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for graDinamicaSolicitudDato.
    */
    public graDinamicaSolicitudDato() {
		//{{START:CLASS:CONSTRUCTOR
        setMode("dtmf");
		//}}END:CLASS:CONSTRUCTOR
    }

}

