package flow;

import com.avaya.sce.runtimecommon.SCESession;
import com.tp.utils.CustomTracking;
import com.tp.utils.Utils;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public class codMenuEstadoSiniestro extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public codMenuEstadoSiniestro() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		// TODO Auto-generated method stub
		super.requestBegin(mySession);
		try{		
			String value = mySession.getVariableField(IProjectVariables.MEN_ESTADO_SINIESTRO,IProjectVariables.MEN_ESTADO_SINIESTRO_FIELD_VALUE).getStringValue();
			int NoInput = mySession.getVariableField(IProjectVariables.MEN_ESTADO_SINIESTRO,IProjectVariables.MEN_ESTADO_SINIESTRO_FIELD_NOINPUTCOUNT).getIntValue();
			int NoMatch = mySession.getVariableField(IProjectVariables.MEN_ESTADO_SINIESTRO,IProjectVariables.MEN_ESTADO_SINIESTRO_FIELD_NOMATCHCOUNT).getIntValue();
			int Repeticiones = mySession.getVariableField(IProjectVariables.VAR_CONFIGURACION,IProjectVariables.VAR_CONFIGURACION_FIELD_REPETICIONES).getIntValue();
			
			int IntentosMenu = mySession.getVariable(IProjectVariables.INTENTOS_MENU).getSimpleVariable().getIntValue();
			IntentosMenu = IntentosMenu + 1;
			mySession.getVariable(IProjectVariables.INTENTOS_MENU).getSimpleVariable().setValue(IntentosMenu);


			if(NoInput >= 1) {
				Utils.agregarOpcion("NoInput", "No ingreso opción - Menú Estado Siniestro", mySession, "", "", "", "", "9", "5");				
			}else {
				if (NoMatch >= 1) {
					Utils.agregarOpcion("NoMatch", "Opción no valida - Menú Estado Siniestro", mySession, "", "", "", "", "9", "5");			
				}else {	
					switch (value) {
					case "1":
						mySession.getVariable(IProjectVariables.OPCION_MENU).getSimpleVariable().setValue("1. Para solicitar orientación para el pago de gastos funerarios");
						Utils.agregarOpcion("Opcion1", "Opción 1 - Para solicitar orientación para el pago de gastos funerarios", mySession, "", "", "", "1", "9", "5");
						mySession.getVariable(IProjectVariables.INTENTOS_MENU).getSimpleVariable().setValue("0");
						break;
					case "2":
						mySession.getVariable(IProjectVariables.OPCION_MENU).getSimpleVariable().setValue("2. De lo contrario permanezca en linea");
						Utils.agregarOpcion("Opcion2", "Opción de lo contrario permanezca en linea", mySession, "", "", "", "2", "9", "5");		
						mySession.getVariable(IProjectVariables.INTENTOS_MENU).getSimpleVariable().setValue("0");		
						break;
					}
				}
			}
			
			if(IntentosMenu >= Repeticiones) {
				Utils.agregarOpcion("ExcedeIntentos", "Excede intentos - Menú Estado Siniestro", mySession, "", "", "", "", "9", "5");
			}
		}catch(Exception ex){
			CustomTracking.error(mySession, ex.getMessage());
		}
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "menEstadoSiniestro:noinputcount", com.avaya.sce.runtime.Expression.INT_GREATER_THEN_EQUAL, "1", false).setDebugId(5822)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("datValidaIntentosMenuEstadoSiniestro", "NoInput").setDebugId(5823));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}


		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "menEstadoSiniestro:nomatchcount", com.avaya.sce.runtime.Expression.INT_GREATER_THEN_EQUAL, "1", false).setDebugId(5824)).evaluate(mySession)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("vdnDesborde", "varConfiguracion:vdnEstadoSiniestroOP2", false).setDebugId(5853));
			actions.add(new com.avaya.sce.runtime.Next("datValidaIntentosMenuEstadoSiniestro", "NoMatch").setDebugId(5825));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}


		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "menEstadoSiniestro:value", com.avaya.sce.runtime.Expression.STRING_EQUAL, "1", false).setDebugId(5826)).evaluate(mySession)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("vdnDesborde", "varConfiguracion:vdnEstadoSiniestroOP1", false).setDebugId(5827));
			actions.add(new com.avaya.sce.runtime.Next("datTransferencia", "1").setDebugId(5828));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}


		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition4", "menEstadoSiniestro:value", com.avaya.sce.runtime.Expression.STRING_EQUAL, "2", false).setDebugId(5979)).evaluate(mySession)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("vdnDesborde", "varConfiguracion:vdnEstadoSiniestroOP2", false).setDebugId(5980));
			actions.add(new com.avaya.sce.runtime.Next("datTransferencia", "2").setDebugId(5981));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
