package flow.subflow.sbfAudioTexto;

import com.tp.utils.Audio;
import com.tp.utils.CustomTracking;
import com.tp.utils.InformacionAudios;

import flow.IProjectVariables;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public class svlRecuperarAudio extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public svlRecuperarAudio() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}
	
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!
		try
		{
			
			String AssociatedCode1 = mySession.getVariable(IProjectVariables.ASSOCIATED_CODE_1).getSimpleVariable().getStringValue(); 
					
			InformacionAudios objAudios = new InformacionAudios();
			Audio audio = objAudios.buscarPorCodigo(AssociatedCode1, mySession);
			
			mySession.getVariable(IProjectVariables.URL_AUDIO).getSimpleVariable().setValue("");
			mySession.getVariable(IProjectVariables.ASSOCIATED_CODE_1).getSimpleVariable().setValue(audio.getCodigoAsociado1());
			mySession.getVariable(IProjectVariables.ASSOCIATED_CODE_2).getSimpleVariable().setValue(audio.getCodigoAsociado2());
			
			if(audio.getActivo())
			{
				if(!audio.getAudioFile().equalsIgnoreCase("") && audio.getAudioFile().contains(".wav")) 
				{
					mySession.getVariable(IProjectVariables.URL_AUDIO).getSimpleVariable().setValue(audio.getUrlAudio());
				}
			}
		}
		catch(Exception ex)
		{
			CustomTracking.error(mySession,ex.getMessage());
		}
	}

	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("sbfAudioTexto-datValidaURLAudio", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
